// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2XQjlDUn4UFZk-smMXOmjhaAs_dBLrgY',
    appId: '1:807655370598:web:157149ef3beff4fdc622a7',
    messagingSenderId: '807655370598',
    projectId: 'vitalrise-28ba2',
    authDomain: 'vitalrise-28ba2.firebaseapp.com',
    storageBucket: 'vitalrise-28ba2.firebasestorage.app',
    measurementId: 'G-2VGMKM5Z9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWCte6VegUJcMroejuaz2Wx3gx9fP2WDI',
    appId: '1:807655370598:android:d9d5f05092c3aeb1c622a7',
    messagingSenderId: '807655370598',
    projectId: 'vitalrise-28ba2',
    storageBucket: 'vitalrise-28ba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWtXQKnxSS8ll79aayyAUEntTDKaq5BJQ',
    appId: '1:807655370598:ios:bd1a79dc7a6e6af2c622a7',
    messagingSenderId: '807655370598',
    projectId: 'vitalrise-28ba2',
    storageBucket: 'vitalrise-28ba2.firebasestorage.app',
    iosBundleId: 'com.example.nutritionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWtXQKnxSS8ll79aayyAUEntTDKaq5BJQ',
    appId: '1:807655370598:ios:bd1a79dc7a6e6af2c622a7',
    messagingSenderId: '807655370598',
    projectId: 'vitalrise-28ba2',
    storageBucket: 'vitalrise-28ba2.firebasestorage.app',
    iosBundleId: 'com.example.nutritionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2XQjlDUn4UFZk-smMXOmjhaAs_dBLrgY',
    appId: '1:807655370598:web:1d87dc116059b565c622a7',
    messagingSenderId: '807655370598',
    projectId: 'vitalrise-28ba2',
    authDomain: 'vitalrise-28ba2.firebaseapp.com',
    storageBucket: 'vitalrise-28ba2.firebasestorage.app',
    measurementId: 'G-7DVB8FBSL0',
  );

}